name: Security Audit

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  dependances:
    name: Check Dependencies (Pip)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Scan de requirements.txt avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'requirements.txt'
          format: 'table'
          exit-code: '1'                 
          severity: 'CRITICAL,HIGH'     


  dockerfile_check:
    name: Check Dockerfile (Config)
    runs-on: ubuntu-latest
    needs: dependances
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Scan du Dockerfile avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'            # Mode 'config' pour analyser les mauvaises pratiques Docker
          scan-ref: 'Dockerfile'
          format: 'table'
          exit-code: '1'                 # Fait Ã©chouer le job si mauvaises pratiques (ex: user root)
          severity: 'CRITICAL,HIGH'
